### ISSUE TITLE
Truncated jar exceptions - Test files missing

### ISSUE THREAD

**Issue by VangelisTheodorakis** [UcarLab/ATAC-DoubletDetector#19]
Hi,

I am trying to run the snATACOverlapCounter.jar through the AMULET.sh, but it fails, and the error message is truncated, so not helpful at all. Most probably, my input files are not shaped properly. Can you provide the test files in the examples and/or a better representation of the errors?

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 9
	at org.jax.snatacoverlapcounter.util.Util.readCellBarcodes(Util.java:56)
	at org.jax.snatacoverlapcounter.OverlapCounter.findOverlaps(OverlapCounter.java:203)
	at org.jax.snatacoverlapcounter.OverlapCounter.main(OverlapCounter.java:134)
	... 5 more
```

**Comment by ajt986** [comment]
Hello,

The problem is with the input csv file. It's trying to use a column that isn't there. By default it's looking for the column at index 9 where the first column would be index 0. This column contains values of 1 if the row is a detected cell. It's necessary so that the program knows which of the barcodes correspond to cells that will be used in the analysis.

To fix this, identify the column in the CSV file that determines whether or not the current barcode corresponds to a cell (values of 1 means it's a cell) and count index of that column. Afterwards, use the `--iscellidx` option when running AMULET.sh

We'll work on adding test inputs for a future update. For now, hopefully the above fix will work for you.
